const dbTableColors = {
  web_decks: "Random",
  "Rustbolt": "Orange",
  "Z-Mech": "Purple",
  "Citron": "White",
  "Green Shadow": "White",
  "Beta-Carrotina": "White",
  "Brain Freeze": "Blue",
  "Captain Combustible": "Green",
  "Chompzilla": "Yellow",
  "Electric Boogaloo": "Purple",
  "Grass Knuckles": "#964B00",
  "Huge-Gigantacus": "#000000",
  "Super Brainz": "#000000",
  "Impfinity": "#000000",
  "Immorticia": "Blue",
  "Night Cap": "White",
  "Neptuna": "#000000",
  "Professor Brainstorm": "Purple",
  "Rose": "Yellow",
  "Solar Flare": "Yellow",
  "The Smash": "Blue",
  "Spudow": "#964B00",
  "Wall-Knight": "Yellow",
  guardiancards: "#964B00",
  guardiantricks: "#964B00",
  kabloomcards: "Red",
  kabloomtricks: "Red",
  megagrowcards: "Green",
  megagrowtricks: "Green",
  smartycards: "White",
  smartytricks: "White",
  solarcards: "Yellow",
  solartricks: "Yellow",
  beastlycards: "Blue",
  beastlytricks: "Blue",
  brainycards: "Purple",
  brainytricks: "Purple",
  crazycards: "Purple",
  crazytricks: "Purple",
  heartycards: "Orange",
  heartytricks: "Orange",
  sneakycards: "#000000",
  sneakytricks: "#000000"
};

module.exports = dbTableColors;