const dbTableColors = {
  rbdecks: "Orange",
  zmdecks: "Purple",
  ctdecks: "White",
  gsdecks: "White",
  bcdecks: "White",
  bfdecks: "Blue",
  ccdecks: "Green",
  czdecks: "Yellow",
  ebdecks: "Purple",
  gkdecks: "#964B00",
  hgdecks: "#000000",
  sbdecks: "#000000",
  ifdecks: "#000000",
  imdecks: "Blue",
  ncdecks: "White",
  ntdecks: "#000000",
  pbdecks: "Purple",
  rodecks: "Yellow",
  sfdecks: "Yellow",
  smdecks: "Blue",
  spdecks: "#964B00",
  wkdecks: "Yellow",
  guardiancards: "#964B00",
  guardiantricks: "#964B00",
  kabloomcards: "Red",
  kabloomtricks: "Red",
  megagrowcards: "Green",
  megagrowtricks: "Green",
  smartycards2: "White",
  smartytricks: "White",
  solarcards: "Yellow",
  solartricks: "Yellow",
  beastlycards: "Blue",
  beastlytricks: "Blue",
  brainycards: "Purple",
  brainytricks: "Purple",
  crazycards: "Purple",
  crazytricks: "Purple",
  heartycards: "Orange",
  heartytricks: "Orange",
  sneakycards: "#000000",
  sneakytricks: "#000000"
};

module.exports = dbTableColors;
